apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: init-message
    image: busybox
    command: ['echo', 'Initializing application...']
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80