apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZGloaWEtZ3VlbXJhb3VpIiwicGFzc3dvcmQiOiJnaHBfVm9wb1RRcWpHOW9Qb1F0Z2FVSVI1a0FvMDE2YlgxMHV0MWF2IiwiYXV0aCI6IlpHbG9hV0V0WjNWbGJYSmhiM1ZwT21kb2NGOVdiM0J2VkZGeGFrYzViMUJ2VVhSbllWVkpValZyUVc4d01UWmlXREV3ZFhReFlYWT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
